on:
  push:
    branches:
      - main
name: Build
jobs:
  test:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.2,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          xcodebuild clean build test -project tourism.xcodeproj -scheme tourism -destination "${destination}" CODE_SIGN_IDENTITY="c444a320-5b60-4b2d-aa08-4dd3322e6d43" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}
